freeze_until_layer: 20
learning_rate: 0.001
num_classes: 18
pos_weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADg2Nzc1MzM3NnECWAMAAABjcHVxA0sSTnRxBFEugAJdcQBYCQAAADg2Nzc1MzM3
    NnEBYS4SAAAAAAAAAG7bJkH+VpNBbtuGQd/3bUHgD2hBoCl0QeeHNUEyB+FA5ySIQdr+/kAAADhB
    0iDFQZts0kAcxyFBpagHQVLiV0G7L39BgKCoQA==
- 0
- !!python/tuple
  - 18
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
