learning_rate: 0.001
num_classes: 18
pos_weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYCQAAADU3NzU1NjQ0OHECWAMAAABjcHVxA0sSTnRxBFEugAJdcQBYCQAAADU3NzU1NjQ0
    OHEBYS4SAAAAAAAAAF8FI0GFN5JB+tGHQWmigUEhd21B+/pqQUUgR0F4OeVAXiCLQZUI/kDNzDxB
    jbDUQW6n0kDKaxhBl5YGQXGhVkEAAHBBT+ykQA==
- 0
- !!python/tuple
  - 18
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
